--1
SELECT COUNT(*) - COUNT(DISTINCT CITY) FROM STATION

--2
SELECT
    CITY, LENGTH(CITY)
FROM
    STATION
WHERE
    LENGTH(CITY) = (SELECT MIN(LENGTH(CITY)) FROM STATION)
ORDER BY
    CITY ASC
LIMIT 1;

SELECT
    CITY, LENGTH(CITY)
FROM
    STATION
WHERE
    LENGTH(CITY) = (SELECT MAX(LENGTH(CITY)) FROM STATION)
ORDER BY
     CITY DESC
LIMIT 1;

--3
SELECT
    DISTINCT CITY
FROM
    STATION
WHERE
    CITY LIKE 'A%' OR CITY LIKE 'E%' OR CITY LIKE 'I%' OR CITY LIKE 'O%' OR CITY LIKE 'U%';

--4
SELECT
    DISTINCT CITY
FROM
    STATION
WHERE
    CITY LIKE '%A' OR CITY LIKE '%E' OR CITY LIKE '%I' OR CITY LIKE '%O' OR CITY LIKE '%U';

--5
SELECT
    DISTINCT CITY
FROM
    STATION
WHERE
    (CITY LIKE 'A%' OR CITY LIKE 'E%' OR CITY LIKE 'I%' OR CITY LIKE 'O%' OR CITY LIKE 'U%') AND
    (CITY LIKE '%A' OR CITY LIKE '%E' OR CITY LIKE '%I' OR CITY LIKE '%O' OR CITY LIKE '%U');

--6
SELECT
    DISTINCT CITY
FROM
    STATION
WHERE
    CITY NOT LIKE 'A%' AND CITY NOT LIKE 'E%' AND CITY NOT LIKE 'I%' AND CITY NOT LIKE 'O%' AND CITY NOT LIKE 'U%'

--7
SELECT
    DISTINCT CITY
FROM
    STATION
WHERE
    CITY NOT LIKE '%A' AND CITY NOT LIKE '%E' AND CITY NOT LIKE '%I' AND CITY NOT LIKE '%O' AND CITY NOT LIKE '%U'

--8
SELECT
    DISTINCT CITY
FROM
    STATION
WHERE
    (CITY NOT LIKE 'A%' AND CITY NOT LIKE 'E%' AND CITY NOT LIKE 'I%' AND CITY NOT LIKE 'O%' AND CITY NOT LIKE 'U%') OR
    (CITY NOT LIKE '%A' AND CITY NOT LIKE '%E' AND CITY NOT LIKE '%I' AND CITY NOT LIKE '%O' AND CITY NOT LIKE '%U');

--9
SELECT
    DISTINCT CITY
FROM
    STATION
WHERE
    (CITY NOT LIKE 'A%' AND CITY NOT LIKE 'E%' AND CITY NOT LIKE 'I%' AND CITY NOT LIKE 'O%' AND CITY NOT LIKE 'U%') AND
    (CITY NOT LIKE '%A' AND CITY NOT LIKE '%E' AND CITY NOT LIKE '%I' AND CITY NOT LIKE '%O' AND CITY NOT LIKE '%U');

--10

